### ISSUE TITLE
tool issue 

### ISSUE THREAD

**Issue by Ravikm941** [zidansec/subscan#1]
after run the tool there is n information and output

**Comment by Visalyputra** [comment]
I think it is because of the api url in the code is not working.

**Comment by zidansec** [comment]
> I think it is because of the api url in the code is not working.

Yes, I've fixed it. Now it can be reused. Try running the subscan again.

**Comment by Visalyputra** [comment]
yes, it fixed, but still no result after running the code it does not get any subdomains.
